title: OpenR Documents
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://iamlilAJ.github.io/OpenR-docs

aux_links:
  Template Repository: https://github.com/iamlilAJ/OpenR-docs
